"use strict";
exports.__esModule = true;
exports.router = void 0;
var express_1 = require("express");
var appController_1 = require("../controllers/appController");
exports.router = (0, express_1.Router)();
exports.router.get("/api/citizens", appController_1.controller.getCitizens);
exports.router.get("/api/citizens/:id", appController_1.controller.getCitizen);
exports.router.post("/api/citizens", appController_1.controller.addNewCitizen);
exports.router.put("/api/citizens/:id", appController_1.controller.updateCitizen);
exports.router["delete"]("/api/citizens/:id", appController_1.controller.deleteCitizen);
